#!/usr/bin/env python3
"""Merge HTML section pages into continuous PDF chapter sources.

The chapter/section relationship is inferred from book.chapters in _quarto-html.yml:
a chapter/*.qmd page followed by chapter/<folder>/*.qmd owns that folder. Each
folder is merged to pdf-merged/<folder>.qmd, and _quarto-pdf.yml is regenerated
so the PDF build reads only the merged chapter files.
"""

from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "_quarto-html.yml"
PROFILE = ROOT / "_quarto-pdf.yml"
OUTPUT_DIR = ROOT / "pdf-merged"


def read_book_chapters() -> list[str]:
    lines = CONFIG.read_text(encoding="utf-8").splitlines()
    try:
        start = lines.index("  chapters:") + 1
    except ValueError as error:
        raise ValueError("_quarto-html.yml has no book.chapters list") from error

    chapters: list[str] = []
    for line in lines[start:]:
        if line.startswith("    - "):
            value = line[6:].strip().strip('"').strip("'")
            if value.endswith(".qmd"):
                chapters.append(value)
        elif line.startswith("  ") and not line.startswith("    "):
            break
    return chapters


def section_for_pdf(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or not lines[0].startswith("# "):
        raise ValueError(f"{path}: first line must be a level-one heading")

    title = lines[0][2:].strip()
    suffix = " {.unnumbered}"
    if title.endswith(suffix):
        title = title[: -len(suffix)].rstrip()

    # Remove legacy hand-written numbers during migration, if present.
    first_word, separator, remainder = title.partition(" ")
    if separator and first_word.count(".") == 1:
        left, right = first_word.split(".")
        if left.isdigit() and right.isdigit():
            title = remainder

    body = "\n".join(lines[1:]).strip()
    return f"## {title}\n\n{body}\n"


def discover_groups(chapters: list[str]) -> tuple[dict[str, dict], dict[str, str]]:
    groups: dict[str, dict] = {}
    parent_to_folder: dict[str, str] = {}
    current_parent: str | None = None

    for entry in chapters:
        parts = PurePosixPath(entry).parts
        if len(parts) >= 3 and parts[0] == "chapter" and parts[1].startswith("chapter"):
            if current_parent is None:
                raise ValueError(f"{entry}: no preceding chapter page")
            folder = parts[1]
            group = groups.setdefault(folder, {"parent": current_parent})
            if group["parent"] != current_parent:
                raise ValueError(f"sections/{folder} is assigned to multiple chapters")
            parent_to_folder[current_parent] = folder
        else:
            current_parent = entry

    return groups, parent_to_folder


def merge_group(folder: str, parent: str) -> str:
    section_dir = ROOT / "chapter" / folder
    sections = sorted(section_dir.glob("*.qmd"))
    if not sections:
        raise ValueError(f"{section_dir}: no .qmd section files found")

    parent_text = (ROOT / parent).read_text(encoding="utf-8").rstrip()
    combined = [parent_text]
    combined.extend(section_for_pdf(path).rstrip() for path in sections)

    output = OUTPUT_DIR / f"{folder}.qmd"
    output.write_text("\n\n".join(combined) + "\n", encoding="utf-8")
    return output.relative_to(ROOT).as_posix()


def write_pdf_profile(pdf_chapters: list[str]) -> None:
    chapter_lines = "\n".join(f"    - {path}" for path in pdf_chapters)
    profile = f"""# Generated by scripts/build_pdf_sources.py; do not edit manually.
project:
  output-dir: _book-pdf

book:
  chapters:
{chapter_lines}

format:
  elegantbook-pdf:
    resource-path:
      - .
"""
    PROFILE.write_text(profile, encoding="utf-8")


def main() -> None:
    chapters = read_book_chapters()
    groups, parent_to_folder = discover_groups(chapters)

    OUTPUT_DIR.mkdir(exist_ok=True)
    for stale in OUTPUT_DIR.glob("*.qmd"):
        stale.unlink()

    merged_paths = {
        parent: merge_group(folder, parent)
        for parent, folder in parent_to_folder.items()
    }

    pdf_chapters: list[str] = []
    emitted_parents: set[str] = set()
    for entry in chapters:
        parts = PurePosixPath(entry).parts
        if len(parts) >= 3 and parts[0] == "chapter" and parts[1].startswith("chapter"):
            continue
        if entry in merged_paths:
            if entry not in emitted_parents:
                pdf_chapters.append(merged_paths[entry])
                emitted_parents.add(entry)
        else:
            pdf_chapters.append(entry)

    write_pdf_profile(pdf_chapters)
    for folder in groups:
        print(f"chapter/{folder} -> pdf-merged/{folder}.qmd")


if __name__ == "__main__":
    main()
